# Generated by Django 4.2.3 on 2024-05-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectgrade',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='subject',
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='art_and_design',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='biology',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='chemistry',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='computer_science',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='english',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='geography',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='history',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='kiswahili',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='mathematics',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='music',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='physical_education',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='physics',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='religious_education',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
