# Generated by Django 4.2.3 on 2024-05-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_subjectgrade_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectgrade',
            old_name='art_and_design',
            new_name='art_and_design_grade',
        ),
        migrations.RenameField(
            model_name='subjectgrade',
            old_name='biology',
            new_name='biology_grade',
        ),
        migrations.RenameField(
            model_name='subjectgrade',
            old_name='chemistry',
            new_name='chemistry_grade',
        ),
        migrations.RenameField(
            model_name='subjectgrade',
            old_name='computer_science',
            new_name='computer_science_grade',
        ),
        migrations.RenameField(
            model_name='subjectgrade',
            old_name='english',
            new_name='english_grade',
        ),
        migrations.RenameField(
            model_name='subjectgrade',
            old_name='geography',
            new_name='geography_grade',
        ),
        migrations.RenameField(
            model_name='subjectgrade',
            old_name='history',
            new_name='history_grade',
        ),
        migrations.RenameField(
            model_name='subjectgrade',
            old_name='kiswahili',
            new_name='kiswahili_grade',
        ),
        migrations.RenameField(
            model_name='subjectgrade',
            old_name='mathematics',
            new_name='mathematics_grade',
        ),
        migrations.RenameField(
            model_name='subjectgrade',
            old_name='music',
            new_name='music_grade',
        ),
        migrations.RenameField(
            model_name='subjectgrade',
            old_name='physical_education',
            new_name='physical_education_grade',
        ),
        migrations.RenameField(
            model_name='subjectgrade',
            old_name='physics',
            new_name='physics_grade',
        ),
        migrations.RenameField(
            model_name='subjectgrade',
            old_name='religious_education',
            new_name='religious_education_grade',
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='art_and_design_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='biology_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='chemistry_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='computer_science_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='english_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='geography_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='history_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='kiswahili_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='mathematics_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='music_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='physical_education_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='physics_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='religious_education_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
