# Generated by Django 4.2.3 on 2024-08-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_remove_studentprofile_class_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_img.jpeg', upload_to='student_profiles'),
        ),
    ]
