# Generated by Django 4.2.3 on 2024-08-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_img.jpeg', upload_to='School_Users_profiles'),
        ),
    ]
