# Generated by Django 4.2.3 on 2024-08-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
