# Generated by Django 4.2.3 on 2024-08-05 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10, unique=True)),
                ('username', models.CharField(default='student', max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_title', models.CharField(default='Kianyaga boys form 4 exam', max_length=50)),
                ('chemistry_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chemistry_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('mathematics_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mathematics_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('physics_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('physics_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('biology_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('biology_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('history_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('history_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('geography_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('geography_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('english_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('english_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('kiswahili_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('kiswahili_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('computer_science_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('computer_science_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('art_and_design_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('art_and_design_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('music_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('music_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('physical_education_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('physical_education_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('religious_education_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('religious_education_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('resource_description', models.TextField()),
                ('resource_file', models.FileField(upload_to='student/resources')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTeachersComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_discipline', models.TextField()),
                ('comment_on_accademics', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='AverageGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_title', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=2)),
                ('date_recorded', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='average_grades', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('due_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='students.student')),
            ],
        ),
    ]
