# Generated by Django 4.2.3 on 2024-08-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classteacherscomment',
            old_name='comment_on_accademics',
            new_name='comment_on_academics',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='student',
        ),
    ]
