# Generated by Django 4.2.3 on 2024-08-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='student',
        ),
    ]
