# Generated by Django 4.2.3 on 2024-08-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_user_profile_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='student_default_img.jpg', upload_to='student_profiles'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='student_default_img.jpg', upload_to='student_profiles'),
        ),
    ]
