# Generated by Django 4.2.3 on 2024-08-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_image_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
