# Generated by Django 4.2.3 on 2024-08-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_class_rename_student_profile_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_assigned',
            field=models.CharField(choices=[('form 1', 'form 1'), ('form 2', 'form 2'), ('form 3', 'form 3'), ('form 4', 'form 4')], default='form 1', max_length=6),
        ),
    ]
