# Generated by Django 4.2.3 on 2024-08-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_class_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_assigned',
            field=models.CharField(choices=[('form 1', 'form 1'), ('form 2', 'form 2'), ('form 3', 'form 3'), ('form 4', 'form 4')], max_length=6),
        ),
    ]
