# Generated by Django 4.2.3 on 2024-08-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_student_class_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Student',
            new_name='student',
        ),
    ]
