# Generated by Django 4.2.3 on 2024-08-14 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_rename_student_profile_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_assigned',
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.class'),
        ),
    ]
