# Generated by Django 4.2.3 on 2024-08-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_remove_student_class_assigned_student_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(default='student', max_length=30, unique=True),
        ),
    ]
