# Generated by Django 4.2.3 on 2024-08-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_resources_student_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='student',
        ),
    ]
