# Generated by Django 4.2.3 on 2024-08-22 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_remove_resources_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='students.student'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
