# Generated by Django 4.2.3 on 2024-08-22 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_resources_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='student',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='students.student'),
        ),
    ]
