# Generated by Django 4.2.3 on 2024-08-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_alter_resources_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='student',
        ),
    ]
