# Generated by Django 4.2.3 on 2024-08-22 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_assignment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='students.student'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='resources',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='students.student'),
        ),
    ]
