# Generated by Django 5.2.7 on 2025-10-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_alter_assignment_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectgrade',
            name='Exam_title',
            field=models.CharField(default='Kianyaga Boys Form 4 Exam', max_length=50),
        ),
    ]
