# Generated by Django 6.0.2 on 2026-03-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_alter_subjectgrade_exam_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectgrade',
            name='art_and_design_grade',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='biology_grade',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='chemistry_grade',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='computer_science_grade',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='english_grade',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='geography_grade',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='history_grade',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='kiswahili_grade',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='mathematics_grade',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='music_grade',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='physical_education_grade',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='physics_grade',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='religious_education_grade',
        ),
    ]
