# Generated by Django 6.0.2 on 2026-05-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_school_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
