# Generated by Django 6.0.2 on 2026-03-06 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('school', '0005_gallery_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
    ]
