# Generated by Django 4.2.3 on 2024-08-15 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_student_username'),
        ('teachers', '0003_alter_teacher_full_name_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.class'),
        ),
    ]
