# Generated by Django 4.2.3 on 2024-08-18 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_alter_teacher_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='username',
        ),
    ]
