# Generated by Django 4.2.3 on 2024-08-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_remove_teacher_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(default='teacher', max_length=20, unique=True),
        ),
    ]
