# Generated by Django 4.2.3 on 2024-08-18 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_teacher_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_teacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='tr_description',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='username',
        ),
    ]
