# Generated by Django 4.2.3 on 2024-08-18 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_student_username'),
        ('teachers', '0011_remove_teacher_class_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(default='1', max_length=30),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tr_description',
            field=models.TextField(default='1'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(default='teacher', max_length=20),
        ),
    ]
