# Generated by Django 4.2.3 on 2024-08-18 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_teacher_class_teacher_teacher_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='username',
        ),
    ]
