# Generated by Django 4.2.3 on 2024-08-18 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_teacher_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='username',
            new_name='tr_username',
        ),
    ]
