# Generated by Django 4.2.3 on 2024-08-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0015_rename_username_teacher_tr_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='tr_username',
        ),
    ]
