# Generated by Django 4.2.3 on 2024-08-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0016_remove_teacher_tr_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='tr_username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
