# Generated by Django 4.2.3 on 2024-08-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0019_teacher_alter_profile_teacher_delete_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='tr_username',
        ),
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
