# Generated by Django 4.2.3 on 2024-08-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0020_remove_teacher_tr_username_teacher_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='username',
        ),
    ]
