# Generated by Django 4.2.3 on 2024-08-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0021_remove_teacher_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
