# Generated by Django 4.2.3 on 2024-08-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0024_remove_teacher_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tr_description',
            field=models.TextField(),
        ),
    ]
