# Generated by Django 4.2.3 on 2024-08-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0025_alter_teacher_full_name_alter_teacher_tr_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
