# Generated by Django 6.0.2 on 2026-05-11 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('teachers', '0028_teacher_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.schoolclass'),
        ),
    ]
