# Generated by Django 4.2.3 on 2024-08-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parents',
        ),
    ]
