# Generated by Django 4.2.3 on 2024-08-22 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_alter_assignment_student_and_more'),
        ('parents', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='full_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='parents',
            name='my_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='students.student'),
        ),
    ]
