# Generated by Django 4.2.3 on 2024-08-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0004_parents_full_name_alter_parents_my_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parents',
            old_name='my_student',
            new_name='My_Student_Adm_No',
        ),
        migrations.AlterField(
            model_name='parents',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
