# Generated by Django 4.2.3 on 2024-08-23 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_alter_assignment_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parents', '0005_rename_my_student_parents_my_student_adm_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='My_Student_Adm_No',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student'),
        ),
        migrations.AlterField(
            model_name='parents',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ParentsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='parents_default_img.jpeg', upload_to='parents_profiles')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parents.parents')),
            ],
        ),
    ]
