# Generated by Django 4.2.3 on 2024-08-23 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parents', '0007_alter_parents_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParentsProfile',
            new_name='Profile',
        ),
        migrations.AlterField(
            model_name='parents',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to=settings.AUTH_USER_MODEL),
        ),
    ]
