# Generated by Django 4.2.3 on 2024-08-23 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0009_alter_parents_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='parents.parents'),
        ),
    ]
