# Generated by Django 4.2.3 on 2024-08-24 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0010_alter_profile_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parents.parents'),
        ),
    ]
