# Generated by Django 4.2.3 on 2024-08-24 09:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_alter_assignment_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parents', '0011_alter_profile_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parents',
            new_name='Parent',
        ),
    ]
