# Generated by Django 6.0.2 on 2026-03-06 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0012_rename_parents_parent'),
        ('school', '0004_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
            preserve_default=False,
        ),
    ]
