# Generated by Django 6.0.2 on 2026-05-11 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('students', '0025_class_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.class'),
        ),
    ]
