# Generated by Django 6.0.2 on 2026-05-11 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_studentmark_school_class'),
        ('students', '0025_class_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0)),
                ('average_score', models.CharField(default=0)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.examtype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.term')),
            ],
        ),
    ]
