# Generated by Django 6.0.2 on 2026-05-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_studentsresults'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsresults',
            old_name='uploaded_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='studentsresults',
            name='subject',
        ),
        migrations.AlterField(
            model_name='studentsresults',
            name='average_score',
            field=models.FloatField(default=0),
        ),
    ]
